//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Domain.olddb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nebulaEntities : DbContext
    {
        public nebulaEntities()
            : base("name=nebulaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaskWithMultipleQuestion> TaskWithMultipleQuestionsOld { get; set; }
        public virtual DbSet<CSQuestion> CSQuestionsOld { get; set; }
    }
}
