//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Domain.olddb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWithMultipleQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskWithMultipleQuestion()
        {
            this.CSQuestions = new HashSet<CSQuestion>();
        }
    
        public int Id { get; set; }
        public string TaskText { get; set; }
        public Nullable<int> TagId { get; set; }
        public bool IsExamPiroba { get; set; }
        public bool IsExercisePiroba { get; set; }
        public Nullable<int> QuestionInfoId { get; set; }
        public Nullable<int> Num { get; set; }
        public bool IsVideoPiroba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSQuestion> CSQuestions { get; set; }
    }
}
