//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Nebula.Web.SocialService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SSAServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SSAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFamilyScoreByPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonScoreByPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonScoreBasisInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFamilyScoreExtendedInfoByPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFamilyScoreFullInfoByPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckFamilyScoresByScoreRangesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScoresByPrivateNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScoresByPrivateNumbersExtOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPersonsUnderPovertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPersonUnderPovertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPersonScoreByScoreRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SSAService() {
            this.Url = global::Nebula.Web.Properties.Settings.Default.ExamsTraining_SocialService_SSAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetFamilyScoreByPIDCompletedEventHandler GetFamilyScoreByPIDCompleted;
        
        /// <remarks/>
        public event GetPersonScoreByPIDCompletedEventHandler GetPersonScoreByPIDCompleted;
        
        /// <remarks/>
        public event GetPersonScoreBasisInfoCompletedEventHandler GetPersonScoreBasisInfoCompleted;
        
        /// <remarks/>
        public event GetFamilyScoreExtendedInfoByPIDCompletedEventHandler GetFamilyScoreExtendedInfoByPIDCompleted;
        
        /// <remarks/>
        public event GetFamilyScoreFullInfoByPIDCompletedEventHandler GetFamilyScoreFullInfoByPIDCompleted;
        
        /// <remarks/>
        public event CheckFamilyScoresByScoreRangesCompletedEventHandler CheckFamilyScoresByScoreRangesCompleted;
        
        /// <remarks/>
        public event GetScoresByPrivateNumbersCompletedEventHandler GetScoresByPrivateNumbersCompleted;
        
        /// <remarks/>
        public event GetScoresByPrivateNumbersExtCompletedEventHandler GetScoresByPrivateNumbersExtCompleted;
        
        /// <remarks/>
        public event CheckPersonsUnderPovertyCompletedEventHandler CheckPersonsUnderPovertyCompleted;
        
        /// <remarks/>
        public event CheckPersonUnderPovertyCompletedEventHandler CheckPersonUnderPovertyCompleted;
        
        /// <remarks/>
        public event CheckPersonScoreByScoreRangeCompletedEventHandler CheckPersonScoreByScoreRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFamilyScoreByPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FamilyScoreInfo GetFamilyScoreByPID(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetFamilyScoreByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((FamilyScoreInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetFamilyScoreByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetFamilyScoreByPIDAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetFamilyScoreByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetFamilyScoreByPIDOperationCompleted == null)) {
                this.GetFamilyScoreByPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFamilyScoreByPIDOperationCompleted);
            }
            this.InvokeAsync("GetFamilyScoreByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetFamilyScoreByPIDOperationCompleted, userState);
        }
        
        private void OnGetFamilyScoreByPIDOperationCompleted(object arg) {
            if ((this.GetFamilyScoreByPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFamilyScoreByPIDCompleted(this, new GetFamilyScoreByPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonScoreByPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonScoreInfo GetPersonScoreByPID(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetPersonScoreByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PersonScoreInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonScoreByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetPersonScoreByPIDAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetPersonScoreByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetPersonScoreByPIDOperationCompleted == null)) {
                this.GetPersonScoreByPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonScoreByPIDOperationCompleted);
            }
            this.InvokeAsync("GetPersonScoreByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetPersonScoreByPIDOperationCompleted, userState);
        }
        
        private void OnGetPersonScoreByPIDOperationCompleted(object arg) {
            if ((this.GetPersonScoreByPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonScoreByPIDCompleted(this, new GetPersonScoreByPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonScoreBasisInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonScoreBasicInfo GetPersonScoreBasisInfo(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetPersonScoreBasisInfo", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PersonScoreBasicInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonScoreBasisInfoAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetPersonScoreBasisInfoAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetPersonScoreBasisInfoAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetPersonScoreBasisInfoOperationCompleted == null)) {
                this.GetPersonScoreBasisInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonScoreBasisInfoOperationCompleted);
            }
            this.InvokeAsync("GetPersonScoreBasisInfo", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetPersonScoreBasisInfoOperationCompleted, userState);
        }
        
        private void OnGetPersonScoreBasisInfoOperationCompleted(object arg) {
            if ((this.GetPersonScoreBasisInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonScoreBasisInfoCompleted(this, new GetPersonScoreBasisInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFamilyScoreExtendedInfoByPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FamilyScoreExtendedInfo GetFamilyScoreExtendedInfoByPID(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetFamilyScoreExtendedInfoByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((FamilyScoreExtendedInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetFamilyScoreExtendedInfoByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetFamilyScoreExtendedInfoByPIDAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetFamilyScoreExtendedInfoByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetFamilyScoreExtendedInfoByPIDOperationCompleted == null)) {
                this.GetFamilyScoreExtendedInfoByPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFamilyScoreExtendedInfoByPIDOperationCompleted);
            }
            this.InvokeAsync("GetFamilyScoreExtendedInfoByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetFamilyScoreExtendedInfoByPIDOperationCompleted, userState);
        }
        
        private void OnGetFamilyScoreExtendedInfoByPIDOperationCompleted(object arg) {
            if ((this.GetFamilyScoreExtendedInfoByPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFamilyScoreExtendedInfoByPIDCompleted(this, new GetFamilyScoreExtendedInfoByPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFamilyScoreFullInfoByPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FamilyScoreFullInfo GetFamilyScoreFullInfoByPID(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetFamilyScoreFullInfoByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((FamilyScoreFullInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetFamilyScoreFullInfoByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetFamilyScoreFullInfoByPIDAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetFamilyScoreFullInfoByPIDAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetFamilyScoreFullInfoByPIDOperationCompleted == null)) {
                this.GetFamilyScoreFullInfoByPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFamilyScoreFullInfoByPIDOperationCompleted);
            }
            this.InvokeAsync("GetFamilyScoreFullInfoByPID", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetFamilyScoreFullInfoByPIDOperationCompleted, userState);
        }
        
        private void OnGetFamilyScoreFullInfoByPIDOperationCompleted(object arg) {
            if ((this.GetFamilyScoreFullInfoByPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFamilyScoreFullInfoByPIDCompleted(this, new GetFamilyScoreFullInfoByPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckFamilyScoresByScoreRanges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FamilyScoreCheckByRangesResult CheckFamilyScoresByScoreRanges(string privateNumber, ScoreRange[] ranges, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("CheckFamilyScoresByScoreRanges", new object[] {
                        privateNumber,
                        ranges,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((FamilyScoreCheckByRangesResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckFamilyScoresByScoreRangesAsync(string privateNumber, ScoreRange[] ranges, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.CheckFamilyScoresByScoreRangesAsync(privateNumber, ranges, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void CheckFamilyScoresByScoreRangesAsync(string privateNumber, ScoreRange[] ranges, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.CheckFamilyScoresByScoreRangesOperationCompleted == null)) {
                this.CheckFamilyScoresByScoreRangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckFamilyScoresByScoreRangesOperationCompleted);
            }
            this.InvokeAsync("CheckFamilyScoresByScoreRanges", new object[] {
                        privateNumber,
                        ranges,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.CheckFamilyScoresByScoreRangesOperationCompleted, userState);
        }
        
        private void OnCheckFamilyScoresByScoreRangesOperationCompleted(object arg) {
            if ((this.CheckFamilyScoresByScoreRangesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckFamilyScoresByScoreRangesCompleted(this, new CheckFamilyScoresByScoreRangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetScoresByPrivateNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PrivateNumbersScoresResultEntity GetScoresByPrivateNumbers(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetScoresByPrivateNumbers", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PrivateNumbersScoresResultEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetScoresByPrivateNumbersAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetScoresByPrivateNumbersAsync(privateNumbers, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetScoresByPrivateNumbersAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetScoresByPrivateNumbersOperationCompleted == null)) {
                this.GetScoresByPrivateNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScoresByPrivateNumbersOperationCompleted);
            }
            this.InvokeAsync("GetScoresByPrivateNumbers", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetScoresByPrivateNumbersOperationCompleted, userState);
        }
        
        private void OnGetScoresByPrivateNumbersOperationCompleted(object arg) {
            if ((this.GetScoresByPrivateNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScoresByPrivateNumbersCompleted(this, new GetScoresByPrivateNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetScoresByPrivateNumbersExt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PrivateNumbersScoresExtResultEntity GetScoresByPrivateNumbersExt(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("GetScoresByPrivateNumbersExt", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PrivateNumbersScoresExtResultEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetScoresByPrivateNumbersExtAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.GetScoresByPrivateNumbersExtAsync(privateNumbers, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void GetScoresByPrivateNumbersExtAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.GetScoresByPrivateNumbersExtOperationCompleted == null)) {
                this.GetScoresByPrivateNumbersExtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScoresByPrivateNumbersExtOperationCompleted);
            }
            this.InvokeAsync("GetScoresByPrivateNumbersExt", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.GetScoresByPrivateNumbersExtOperationCompleted, userState);
        }
        
        private void OnGetScoresByPrivateNumbersExtOperationCompleted(object arg) {
            if ((this.GetScoresByPrivateNumbersExtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScoresByPrivateNumbersExtCompleted(this, new GetScoresByPrivateNumbersExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckPersonsUnderPoverty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PeronsUnderPovertyResultEntity CheckPersonsUnderPoverty(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("CheckPersonsUnderPoverty", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PeronsUnderPovertyResultEntity)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPersonsUnderPovertyAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.CheckPersonsUnderPovertyAsync(privateNumbers, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void CheckPersonsUnderPovertyAsync(string[] privateNumbers, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.CheckPersonsUnderPovertyOperationCompleted == null)) {
                this.CheckPersonsUnderPovertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPersonsUnderPovertyOperationCompleted);
            }
            this.InvokeAsync("CheckPersonsUnderPoverty", new object[] {
                        privateNumbers,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.CheckPersonsUnderPovertyOperationCompleted, userState);
        }
        
        private void OnCheckPersonsUnderPovertyOperationCompleted(object arg) {
            if ((this.CheckPersonsUnderPovertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPersonsUnderPovertyCompleted(this, new CheckPersonsUnderPovertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckPersonUnderPoverty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PeronUnderPovertyResult CheckPersonUnderPoverty(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("CheckPersonUnderPoverty", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PeronUnderPovertyResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPersonUnderPovertyAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.CheckPersonUnderPovertyAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void CheckPersonUnderPovertyAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.CheckPersonUnderPovertyOperationCompleted == null)) {
                this.CheckPersonUnderPovertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPersonUnderPovertyOperationCompleted);
            }
            this.InvokeAsync("CheckPersonUnderPoverty", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.CheckPersonUnderPovertyOperationCompleted, userState);
        }
        
        private void OnCheckPersonUnderPovertyOperationCompleted(object arg) {
            if ((this.CheckPersonUnderPovertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPersonUnderPovertyCompleted(this, new CheckPersonUnderPovertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckPersonScoreByScoreRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonScoreCheckByRangeResult CheckPersonScoreByScoreRange(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            object[] results = this.Invoke("CheckPersonScoreByScoreRange", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID});
            return ((PersonScoreCheckByRangeResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPersonScoreByScoreRangeAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID) {
            this.CheckPersonScoreByScoreRangeAsync(privateNumber, userName, password, sender_ID_DEA, correlationID, null);
        }
        
        /// <remarks/>
        public void CheckPersonScoreByScoreRangeAsync(string privateNumber, string userName, string password, string sender_ID_DEA, string correlationID, object userState) {
            if ((this.CheckPersonScoreByScoreRangeOperationCompleted == null)) {
                this.CheckPersonScoreByScoreRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPersonScoreByScoreRangeOperationCompleted);
            }
            this.InvokeAsync("CheckPersonScoreByScoreRange", new object[] {
                        privateNumber,
                        userName,
                        password,
                        sender_ID_DEA,
                        correlationID}, this.CheckPersonScoreByScoreRangeOperationCompleted, userState);
        }
        
        private void OnCheckPersonScoreByScoreRangeOperationCompleted(object arg) {
            if ((this.CheckPersonScoreByScoreRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPersonScoreByScoreRangeCompleted(this, new CheckPersonScoreByScoreRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyScoreExtendedInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FamilyScoreInfo {
        
        private ResultStatus resultStatusField;
        
        private string familyNumberField;
        
        private System.Nullable<int> familyScoreField;
        
        private System.Nullable<System.DateTime> legalScoreDateField;
        
        private Person[] personsField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyNumber {
            get {
                return this.familyNumberField;
            }
            set {
                this.familyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FamilyScore {
            get {
                return this.familyScoreField;
            }
            set {
                this.familyScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LegalScoreDate {
            get {
                return this.legalScoreDateField;
            }
            set {
                this.legalScoreDateField = value;
            }
        }
        
        /// <remarks/>
        public Person[] Persons {
            get {
                return this.personsField;
            }
            set {
                this.personsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultStatus {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonScoreCheckByRangeResult {
        
        private ResultStatus resultStatusField;
        
        private string privateNumberField;
        
        private bool isInRangeField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PrivateNumber {
            get {
                return this.privateNumberField;
            }
            set {
                this.privateNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInRange {
            get {
                return this.isInRangeField;
            }
            set {
                this.isInRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PeronUnderPovertyResult {
        
        private ResultStatus resultStatusField;
        
        private PeronUnderPovertyResultEntity peronsUnderPovertyField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public PeronUnderPovertyResultEntity PeronsUnderPoverty {
            get {
                return this.peronsUnderPovertyField;
            }
            set {
                this.peronsUnderPovertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PeronUnderPovertyResultEntity {
        
        private string privateNumberField;
        
        private bool isUnderPovertyField;
        
        /// <remarks/>
        public string PrivateNumber {
            get {
                return this.privateNumberField;
            }
            set {
                this.privateNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsUnderPoverty {
            get {
                return this.isUnderPovertyField;
            }
            set {
                this.isUnderPovertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PeronsUnderPovertyResultEntity {
        
        private ResultStatus resultStatusField;
        
        private PeronUnderPovertyResultEntity[] peronsUnderPovertyField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public PeronUnderPovertyResultEntity[] PeronsUnderPoverty {
            get {
                return this.peronsUnderPovertyField;
            }
            set {
                this.peronsUnderPovertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrivateNumberScoreExtResultEntity {
        
        private string privateNumberField;
        
        private System.Nullable<int> scoreField;
        
        private string addressField;
        
        /// <remarks/>
        public string PrivateNumber {
            get {
                return this.privateNumberField;
            }
            set {
                this.privateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrivateNumbersScoresExtResultEntity {
        
        private ResultStatus resultStatusField;
        
        private PrivateNumberScoreExtResultEntity[] privateNumbersScoresField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public PrivateNumberScoreExtResultEntity[] PrivateNumbersScores {
            get {
                return this.privateNumbersScoresField;
            }
            set {
                this.privateNumbersScoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrivateNumberScoreResultEntity {
        
        private string privateNumberField;
        
        private System.Nullable<int> scoreField;
        
        /// <remarks/>
        public string PrivateNumber {
            get {
                return this.privateNumberField;
            }
            set {
                this.privateNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrivateNumbersScoresResultEntity {
        
        private ResultStatus resultStatusField;
        
        private PrivateNumberScoreResultEntity[] privateNumbersScoresField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public PrivateNumberScoreResultEntity[] PrivateNumbersScores {
            get {
                return this.privateNumbersScoresField;
            }
            set {
                this.privateNumbersScoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ScoreRangeResult {
        
        private int minValueField;
        
        private int maxValueField;
        
        private bool isInRangeField;
        
        /// <remarks/>
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInRange {
            get {
                return this.isInRangeField;
            }
            set {
                this.isInRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FamilyScoreCheckByRangesResult {
        
        private ResultStatus resultStatusField;
        
        private Person personField;
        
        private ScoreRangeResult[] scoreRangesResultField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public Person Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public ScoreRangeResult[] ScoreRangesResult {
            get {
                return this.scoreRangesResultField;
            }
            set {
                this.scoreRangesResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Person {
        
        private string privateNumberField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private System.DateTime birthDateField;
        
        private int sexField;
        
        /// <remarks/>
        public string PrivateNumber {
            get {
                return this.privateNumberField;
            }
            set {
                this.privateNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public int Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ScoreRange {
        
        private int minValueField;
        
        private int maxValueField;
        
        /// <remarks/>
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FamilyScore {
        
        private int scoreField;
        
        private System.Nullable<System.DateTime> deklarationFillingDateField;
        
        private System.Nullable<System.DateTime> legalScoreDateField;
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeklarationFillingDate {
            get {
                return this.deklarationFillingDateField;
            }
            set {
                this.deklarationFillingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LegalScoreDate {
            get {
                return this.legalScoreDateField;
            }
            set {
                this.legalScoreDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BankTransfer {
        
        private System.DateTime operationDateField;
        
        private decimal amountField;
        
        /// <remarks/>
        public System.DateTime OperationDate {
            get {
                return this.operationDateField;
            }
            set {
                this.operationDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FamilyScoreFullInfo {
        
        private ResultStatus resultStatusField;
        
        private string familyNumberField;
        
        private string districtField;
        
        private string familyAddressField;
        
        private string authorisedPersonPrivateNumberField;
        
        private string authorisedPersonFullNameField;
        
        private string familyPhonesField;
        
        private System.Nullable<int> scoreField;
        
        private System.Nullable<System.DateTime> deklarationFillingDateField;
        
        private System.Nullable<System.DateTime> legalScoreDateField;
        
        private Person[] personsField;
        
        private BankTransfer[] lastBankTransfersField;
        
        private FamilyScore[] previousScoresField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyNumber {
            get {
                return this.familyNumberField;
            }
            set {
                this.familyNumberField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyAddress {
            get {
                return this.familyAddressField;
            }
            set {
                this.familyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorisedPersonPrivateNumber {
            get {
                return this.authorisedPersonPrivateNumberField;
            }
            set {
                this.authorisedPersonPrivateNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorisedPersonFullName {
            get {
                return this.authorisedPersonFullNameField;
            }
            set {
                this.authorisedPersonFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyPhones {
            get {
                return this.familyPhonesField;
            }
            set {
                this.familyPhonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeklarationFillingDate {
            get {
                return this.deklarationFillingDateField;
            }
            set {
                this.deklarationFillingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LegalScoreDate {
            get {
                return this.legalScoreDateField;
            }
            set {
                this.legalScoreDateField = value;
            }
        }
        
        /// <remarks/>
        public Person[] Persons {
            get {
                return this.personsField;
            }
            set {
                this.personsField = value;
            }
        }
        
        /// <remarks/>
        public BankTransfer[] LastBankTransfers {
            get {
                return this.lastBankTransfersField;
            }
            set {
                this.lastBankTransfersField = value;
            }
        }
        
        /// <remarks/>
        public FamilyScore[] PreviousScores {
            get {
                return this.previousScoresField;
            }
            set {
                this.previousScoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonScoreBasicInfo {
        
        private ResultStatus resultStatusField;
        
        private string familyAddressField;
        
        private System.Nullable<int> familyScoreField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyAddress {
            get {
                return this.familyAddressField;
            }
            set {
                this.familyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FamilyScore {
            get {
                return this.familyScoreField;
            }
            set {
                this.familyScoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonScoreInfo {
        
        private ResultStatus resultStatusField;
        
        private string familyNumberField;
        
        private string familyDistrictCodeField;
        
        private string familyDistrictField;
        
        private string familyAddressField;
        
        private System.Nullable<int> familyScoreField;
        
        private System.Nullable<System.DateTime> legalScoreDateField;
        
        private Person personField;
        
        /// <remarks/>
        public ResultStatus ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyNumber {
            get {
                return this.familyNumberField;
            }
            set {
                this.familyNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyDistrictCode {
            get {
                return this.familyDistrictCodeField;
            }
            set {
                this.familyDistrictCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyDistrict {
            get {
                return this.familyDistrictField;
            }
            set {
                this.familyDistrictField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyAddress {
            get {
                return this.familyAddressField;
            }
            set {
                this.familyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FamilyScore {
            get {
                return this.familyScoreField;
            }
            set {
                this.familyScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LegalScoreDate {
            get {
                return this.legalScoreDateField;
            }
            set {
                this.legalScoreDateField = value;
            }
        }
        
        /// <remarks/>
        public Person Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FamilyScoreExtendedInfo : FamilyScoreInfo {
        
        private string districtField;
        
        private string familyAddressField;
        
        private string authorisedPersonPrivateNumberField;
        
        private string authorisedPersonFullNameField;
        
        private string familyPhonesField;
        
        private System.Nullable<decimal> amountField;
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyAddress {
            get {
                return this.familyAddressField;
            }
            set {
                this.familyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorisedPersonPrivateNumber {
            get {
                return this.authorisedPersonPrivateNumberField;
            }
            set {
                this.authorisedPersonPrivateNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorisedPersonFullName {
            get {
                return this.authorisedPersonFullNameField;
            }
            set {
                this.authorisedPersonFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyPhones {
            get {
                return this.familyPhonesField;
            }
            set {
                this.familyPhonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFamilyScoreByPIDCompletedEventHandler(object sender, GetFamilyScoreByPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFamilyScoreByPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFamilyScoreByPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FamilyScoreInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FamilyScoreInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetPersonScoreByPIDCompletedEventHandler(object sender, GetPersonScoreByPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonScoreByPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonScoreByPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonScoreInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonScoreInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetPersonScoreBasisInfoCompletedEventHandler(object sender, GetPersonScoreBasisInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonScoreBasisInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonScoreBasisInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonScoreBasicInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonScoreBasicInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFamilyScoreExtendedInfoByPIDCompletedEventHandler(object sender, GetFamilyScoreExtendedInfoByPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFamilyScoreExtendedInfoByPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFamilyScoreExtendedInfoByPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FamilyScoreExtendedInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FamilyScoreExtendedInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFamilyScoreFullInfoByPIDCompletedEventHandler(object sender, GetFamilyScoreFullInfoByPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFamilyScoreFullInfoByPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFamilyScoreFullInfoByPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FamilyScoreFullInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FamilyScoreFullInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckFamilyScoresByScoreRangesCompletedEventHandler(object sender, CheckFamilyScoresByScoreRangesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckFamilyScoresByScoreRangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckFamilyScoresByScoreRangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FamilyScoreCheckByRangesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FamilyScoreCheckByRangesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetScoresByPrivateNumbersCompletedEventHandler(object sender, GetScoresByPrivateNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScoresByPrivateNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScoresByPrivateNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrivateNumbersScoresResultEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrivateNumbersScoresResultEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetScoresByPrivateNumbersExtCompletedEventHandler(object sender, GetScoresByPrivateNumbersExtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScoresByPrivateNumbersExtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScoresByPrivateNumbersExtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrivateNumbersScoresExtResultEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrivateNumbersScoresExtResultEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckPersonsUnderPovertyCompletedEventHandler(object sender, CheckPersonsUnderPovertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPersonsUnderPovertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPersonsUnderPovertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PeronsUnderPovertyResultEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PeronsUnderPovertyResultEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckPersonUnderPovertyCompletedEventHandler(object sender, CheckPersonUnderPovertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPersonUnderPovertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPersonUnderPovertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PeronUnderPovertyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PeronUnderPovertyResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckPersonScoreByScoreRangeCompletedEventHandler(object sender, CheckPersonScoreByScoreRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPersonScoreByScoreRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPersonScoreByScoreRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonScoreCheckByRangeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonScoreCheckByRangeResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591